apiVersion: apps/v1
kind: Deployment
metadata:
 name: jobportal
spec:
 replicas: 1
 selector:
   matchLabels:
      app: flasknode
 template:
    metadata:
      labels:
        app: flasknode
    spec:
      containers:
      - name: flasknode
        image: icr.io/ibmtest1/NewsApp
        imagePullPolicy: Always
        ports:
        - containerPort: 5000